- name: Configure NGINX container
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy nginx.conf file
      copy:
        src: nginx.conf
        dest: /tmp/nginx.conf

    - name: Run NGINX container
      docker_container:
        name: my-container
        image: nginx:latest
        ports:
          - "8080:80"
        volumes:
          - /tmp/nginx.conf:/etc/nginx/conf.d/default.conf
